[JTC] Renaming varialbes, reodering trajectory checks and fixing open-loop mode by adding last commanded time.
ros-controls/ros2_controllers pull request #1032
Opened 2024-02-09 13:29 UTC by destogl

This PR increseas readability of the JTC by renaming trajectory varialbes to be semantically correct and self explainable.

Also it reoders checks of the trajectories done in the callback. They are grouped based on the things they are checking, i.e., 1. data available, 2. time checks; 3. trajectory point checks.

Additionally, it adds "last_commanded_time_" for the open loop mode to be more correct when setting point before trajectory.

2024-02-12 08:18 UTC, christophfroehlich approved these changes
LGTM and improves readability!

2024-02-12 09:08 UTC, christophfroehlich commented
:eyes: @destogl  `test_no_jump_when_state_tracking_error_not_updated` fails now, I guess due to the `last_commanded_time_` change.

2024-02-12 09:35 UTC, saikishor approved these changes
LGTM, apart from the following minor comment.

Now with the changes, it looks clear and good

2024-02-12 09:35 UTC, saikishor commented on joint_trajectory_controller/src/joint_trajectory_controller.cpp
> +          last_commanded_time_, last_commanded_state_, joints_angle_wraparound_);
In this case, the `last_command_time_` would be same for the first 2 iterations. Is that okay?. If its fine, then all good.

2024-02-19 18:47 UTC, bmagyar submitted a review, later dismissed

2024-11-02 20:19 UTC, christophfroehlich requested changes
This includes #780, which has the same failing test: `test_no_jump_when_state_tracking_error_not_updated`

2025-02-14 22:25 UTC, christophfroehlich submitted a review, later dismissed

2025-02-15 21:11 UTC, saikishor approved these changes
in general, LGTM

2025-02-15 21:11 UTC, saikishor commented on joint_trajectory_controller/src/joint_trajectory_controller.cpp
> +  const auto trajectory_start_time = static_cast<rclcpp::Time>(trajectory.header.stamp);
```suggestion
  const rclcpp::Time trajectory_start_time = trajectory.header.stamp;
```

I don't know if this will work, but I'm guessing yes from here

https://github.com/ros2/rclcpp/blob/19773973a80d753c6fa028b0b548462fbbef122d/rclcpp/src/rclcpp/time.cpp#L109-L114

2025-02-16 12:06 UTC, saikishor commented
@christophfroehlich it seems the downstream builds are failing from the UR drivers scaled JTC. Shall we inform Felix?

2025-02-16 15:11 UTC, christophfroehlich commented
> @christophfroehlich it seems the downstream builds are failing from the UR drivers scaled JTC. Shall we inform Felix?

The changes are simple, I can open a PR for the ur_controllers

2025-02-16 15:15 UTC, christophfroehlich approved these changes

2025-02-16 15:16 UTC, merged