Fix pid_controller build on ROS 2 Rolling on Ubuntu 24.04
ros-controls/ros2_controllers pull request #1084
Opened 2024-03-18 20:44 UTC by clalancette

Two things are needed to make this compile:
1.  Make sure to add a package.xml dependency on backward_ros, which is necessary to compile.
2.  Make sure to #include <rclcpp/version.h>, so the correct rclcpp::QoS object is chosen.

With both of these in place, this package compiles cleanly on Ubuntu 24.04.

This should fix the CI build like in https://build.ros2.org/view/Rbin_uN64/job/Rbin_uN64__pid_controller__ubuntu_noble_amd64__binary/13/console

Contributions via pull requests are much appreciated. Before sending us a pull request, please ensure that:

1. Limited scope. Your PR should do one thing or one set of things. Avoid adding “random fixes” to PRs. Put those on separate PRs.
2. Give your PR a descriptive title. Add a short summary, if required.
3. Make sure the pipeline is green.
4. Don’t be afraid to request reviews from maintainers.
5. New code = new tests. If you are adding new functionality, always make sure to add some tests exercising the code and serving as live documentation of your original intention.

To send us a pull request, please:

- [x] Fork the repository.
- [x] Modify the source; please focus on the specific change you are contributing. If you also reformat all the code, it will be hard for us to focus on your change.
- [x] Ensure local tests pass. (`colcon test` and `pre-commit run` (requires you to install pre-commit by `pip3 install pre-commit`)
- [x] Commit to your fork using clear commit messages.
- [x] Send a pull request, answering any default questions in the pull request interface.
- [x] Pay attention to any automated CI failures reported in the pull request, and stay involved in the conversation.

2024-03-18 21:34 UTC, saikishor requested changes
Thanks for the changes.
Regarding the `backward_ros` dependency, I've just observed the missing dependency in the following packages as well: `ackermann_steering_controller`, `bicycle_steering_controller`, `tricycle_steering_controller`. Can you also add them in the same PR?.

Thank you

2024-03-18 21:34 UTC, saikishor commented on pid_controller/src/pid_controller.cpp
> +#include <rclcpp/version.h>
```suggestion
#include "rclcpp/rclcpp.hpp"
#include "rclcpp/version.h"
```
Thanks for the heads-up on the version header :)

2024-03-19 12:12 UTC, clalancette commented
> Regarding the `backward_ros` dependency, I've just observed the missing dependency in the following packages as well: `ackermann_steering_controller`, `bicycle_steering_controller`, `tricycle_steering_controller`. Can you also add them in the same PR?.

Yes, very good call.  Fixed now in 175c4d5.

2024-03-19 12:16 UTC, saikishor approved these changes
LGTM. Thank you for the changes :)

2024-03-19 12:18 UTC, christophfroehlich approved these changes
Thanks!

2024-03-19 13:33 UTC, clalancette commented
Rolling coverage CI seems to be failing here because the action is not installing `ros-rolling-rsl` properly in the container.  Then it later fails to build `parameter_traits`, which depends on that.

It doesn't look to be connected with this PR, so I don't think it should hold this up.

2024-03-21 06:27 UTC, bmagyar approved these changes
Brilliant, thank you!

2024-03-21 06:27 UTC, merged

2024-03-21 17:33 UTC, clalancette commented
A release into Rolling would be much appreciated, as it would close out this particular problem.  Thanks!