[STEERING] Add missing `tan` call for ackermann
ros-controls/ros2_controllers pull request #1117
Opened 2024-05-06 08:52 UTC by qinqon

The steering library is missing a call to calculate tangent from steering pos at ackermann code.

2024-05-06 08:59 UTC, qinqon commented
@saikishor FYI

2024-05-06 09:09 UTC, saikishor requested changes
@qinqon It would be great if you can also update the docs with some references to the actual math, so we can avoid this in future. 

Will you be able to add some tests?

2024-05-07 09:19 UTC, christophfroehlich commented
Regarding docs: No, the original author did not include any. Please have a look at #954 and review what I've written there.

2024-05-07 09:45 UTC, christophfroehlich commented
> @christophfroehlich someting a little off topic, I am preparing a PR to implement swerve drive re-using/refactoring steering library, does it make sense, or is better to create a new controller ?

Please open a separate issue and propose your changes. I also had a rewrite of the steering library in mind, maybe we can find a proper way going forward. We can also discuss this on slack, I can add ellorent@redhat.com if you want?

2024-05-07 10:03 UTC, qinqon commented
> > @christophfroehlich someting a little off topic, I am preparing a PR to implement swerve drive re-using/refactoring steering library, does it make sense, or is better to create a new controller ?
> 
> Please open a separate issue and propose your changes. I also had a rewrite of the steering library in mind, maybe we can find a proper way going forward. We can also discuss this on slack, I can add [ellorent@redhat.com](mailto:ellorent@redhat.com) if you want?

Can you add me with my personal email ? quique.llorente@gmail.com

2024-06-08 12:53 UTC, christophfroehlich commented
@qinqon this is still missing? I can include it in #1150

2024-06-08 12:54 UTC, christophfroehlich approved these changes

2024-06-08 12:56 UTC, christophfroehlich commented on steering_controllers_library/src/steering_odometry.cpp
> +  const double angular_velocity = tan(steer_pos_) * linear_velocity / wheelbase_;
```suggestion
  const double angular_velocity = std::tan(steer_pos_) * linear_velocity / wheelbase_;
```

2024-06-11 05:44 UTC, christophfroehlich commented on steering_controllers_library/src/steering_odometry.cpp
> +  const double angular_velocity = tan(steer_pos_) * linear_velocity / wheelbase_;
I did that already in the other steering library PR -> we well have merge conflicts now ;)

2024-06-11 12:33 UTC, christophfroehlich approved these changes

2024-06-19 17:30 UTC, bmagyar approved these changes

2024-06-19 17:31 UTC, merged