Remove unstamped twist subscribers + parameters
ros-controls/ros2_controllers pull request #1151
Opened 2024-05-26 17:55 UTC by christophfroehlich

Removes the earlier already deprecated unstamped twist subscribers.

Closes #989

2024-05-27 20:20 UTC, saikishor requested changes
Just a minor comment

2024-05-27 20:20 UTC, saikishor commented on steering_controllers_library/src/steering_controllers_library.cpp
> +    "[Deprecated] Using geometry_msgs::msg::Twist instead of TwistStamped is deprecated.");
```suggestion
```
As we are completely removing, I don't see a point of printing the depreciation notice

2024-05-27 22:13 UTC, christophfroehlich commented
> Just a minor comment

not minor, the deprecation note was in the wrong section anyways :D it was shown when the correct message type was used.

2024-05-27 22:36 UTC, saikishor approved these changes
LGTM

2024-06-05 18:14 UTC, bmagyar approved these changes

2024-06-05 18:14 UTC, merged