[WIP] Remove front_steering from steering library
ros-controls/ros2_controllers pull request #1166
Opened 2024-06-08 07:49 UTC by qinqon

To Accommodate controllers that are not only steering at front or rear this change remove the `front_steering` variable from steering_controller_library, as a byproduct of that the the notino of front or rear wheel radius is also removed from dependant controllers and the library has know "wheels" and "steers" joints.

2024-06-08 12:42 UTC, christophfroehlich requested changes
I support the idea, thanks!

Please deprecate the old parameters and add the new ones to support both temporarily. Then we can also backport such changes.

Additionally, please add migration notes [here](https://github.com/ros-controls/ros2_controllers/blob/master/doc/migration/Jazzy.rst).

2024-06-08 12:42 UTC, christophfroehlich commented on steering_controllers_library/src/steering_controllers_library.yaml
> +  wheels_names: {
```suggestion
  traction_wheels_names: {
```
or `traction_joints_names`

2024-06-08 12:42 UTC, christophfroehlich commented on steering_controllers_library/src/steering_controllers_library.yaml
> +  steers_names: {
```suggestion
  steering_wheels_names: {
```
or `steering_joints_names`

2024-06-08 12:44 UTC, christophfroehlich commented
Have you read and considered #692? Ideally, we should solve it with this PR.

2024-06-08 13:29 UTC, qinqon commented
> Have you read and considered #692? Ideally, we should solve it with this PR. 

The idea is the same, is all about generalize the steering library a little more.

> I'm not sure if your proposal works for 4WD + 4x steering?

Next PR will allow that, I am thinking about extending the current ackermann instead of new controller, if you add a pair of traction and steering joints and define the instantaneus center of robot you can have this by modifyting a little the IK and odometry. Also you can keep the current ackermann by configuring the instantaneus centor or robot at the traction joints and using the same IK and odometry.

2024-06-23 13:35 UTC, qinqon commented
Tests woring 
```
$ colcon test 
Starting >>> steering_controllers_library
Finished <<< steering_controllers_library [0.44s]          
Starting >>> ackermann_steering_controller
Starting >>> bicycle_steering_controller
Starting >>> tricycle_steering_controller                                                                    
Finished <<< bicycle_steering_controller [1.50s]                                                                                                   
Finished <<< ackermann_steering_controller [1.58s]                                                            
Finished <<< tricycle_steering_controller [1.52s]

Summary: 4 packages finished [3.01s]

```

2024-07-06 06:56 UTC, bmagyar commented
@destogl please add your take

2024-07-13 06:26 UTC, qinqon commented
@destogl I have rebase the PR, the idea is to prepare a PR based on this one to allow four steering at the ackerman controller.

2024-09-18 21:30 UTC, ARK3r commented
@christophfroehlich I have a suggestion for arbitrarily long robots with an arbitrary number of traction and steering wheels in each "row". So for example:
- bicycle setup 1: 2 rows, one row has a steerable wheel, second row has a traction wheel with the distance between row1 and row2 equal to 1.0 meter (wheelbase)
- bicycle setup 2: 2 rows, one row has a steerable and traction wheel, second row has a steerable and a traction wheel with the distance between row1 and row2 equal to 1.0 meter (wheelbase)
- 6 wheel rover (#1243): 3 rows, row1 has two steerable wheels, row2 only has two steerable + traction wheels, row3 has 1 steerable + traction wheel with (1) row1 having a track of 40 cm and (2) row1 and row2 having a distance of 50 cm (wheelbase) and (3) row2 having a track of 30 cm and (4) row2 and row3 having a distance of 20 cm (wheelbase) and (5) row3 having only one wheel.

so the way each of these can be relayed to the controller could be as follows:

a list (an arbitrarily long number of rows) of lists (info for each row) of [ lists (steerable and traction set) and some other values ] 🫠 where each row's list contains the following info:
```
[ 
   <list of steerable joints in this row: List>,
   <list of traction joints in this row: List>,
   <row track: Union[None, double]>,
   <wheelbase from prev row: Union[None, double]>
]
```
so examples of this would be:

- bicycle setup 1: 
```
[
   [
      ["row1_steering_joint"],
      [ ],
      None,
      None
   ],
   [
      [ ],
      ["row2_traction_joint"],
      None,
      1.0
   ]
]
```
- bicycle setup 2:
```
[
   [
      ["row1_steering_joint"],
      ["row1_traction_joint"],
      None,
      None
   ],
   [
      ["row2_steering_joint" ],
      ["row2_traction_joint"],
      None,
      1.0
   ]
]
```
- 6 wheel rover:
```
[
   [
      ["row1_left_steering_joint", "row1_right_steering_joint"],
      [],
      0.4,
      None
   ],
   [
      ["row2_left_steering_joint", "row2_right_steering_joint" ],
      ["row2_left_traction_joint", "row2_right_traction_joint"],
      0.3,
      0.5
   ],
   [
      ["row3_steering_joint" ],
      ["row3_traction_joint"],
      None,
      0.2
   ]
]
```

2024-09-25 16:59 UTC, christophfroehlich commented
@ARK3r I'm not sure if this is the right place to discuss this (but it would make this PR here obsolete) Let's discuss this in #692

2025-01-03 16:00 UTC, christophfroehlich submitted a review, later dismissed
I unearthed this PR, I changed my mind and think it makes sense to merge this before a possible rewrite of the library.

Thanks @qinqon for the initial work, on top of that I did
- add proper backwards compatibility
- updated the docs
- added migration and release notes
- fixed a bug, that with Ackermann kinematics a different wheel track of the steering and traction axle was not supported (although the parameters were there from the beginning).

2025-01-03 16:46 UTC, Timple commented
It's hard to see on mobile. But I see a separation between tracked and steered wheels.
Can steered wheels also have traction with this pr? We have a vehicle with an active driven front wheel. Would be nice to use this 👍

2025-01-03 16:59 UTC, christophfroehlich commented
> It's hard to see on mobile. But I see a separation between tracked and steered wheels. Can steered wheels also have traction with this pr? We have a vehicle with an active driven front wheel. Would be nice to use this 👍

No, this is is not possible yet. I made a [proposal](https://github.com/ros-controls/ros2_controllers/issues/692#issuecomment-2374731385) once to configure this more freely, but haven't started going in that direction.

2025-01-03 17:20 UTC, ARK3r commented on bicycle_steering_controller/src/bicycle_steering_controller.cpp
```suggestion

  // TODO(anyone): Remove deprecated parameters
  // START OF DEPRECATED
```

2025-01-03 17:21 UTC, ARK3r commented on bicycle_steering_controller/src/bicycle_steering_controller.cpp
> +  const double wheelbase = bicycle_params_.wheelbase;
```suggestion
  // END OF DEPRECATED

  const double wheelbase = bicycle_params_.wheelbase;
```

2025-01-03 20:06 UTC, qinqon commented
> I unearthed this PR, I changed my mind and think it makes sense to merge this before a possible rewrite of the library.
> 
> 
> 
> Thanks @qinqon for the initial work, on top of that I did
> 
> - add proper backwards compatibility
> 
> - updated the docs
> 
> - added migration and release notes
> 
> - fixed a bug, that with Ackermann kinematics a different wheel track of the steering and traction axle was not supported (although the parameters were there from the beginning).

@christophfroehlich happy that the PR did help with the effort, let me know on whatever you need.

2025-02-13 16:30 UTC, skasperski commented
Hello, I am interested in the work here and would like to see it merged. I am currently testing this branch on jazzy and face some issues, probably due to parameterization. Is there any specific order required for `traction_joint_names` and `steering_joint_names` lists? Doesn't it need to know which joints are right and which are left?

@qinqon Are you still working on the 4WD patch? I'd be also willing to contribute or help with testing.

2025-02-13 17:18 UTC, christophfroehlich commented
> Hello, I am interested in the work here and would like to see it merged. I am currently testing this branch on jazzy and face some issues, probably due to parameterization. Is there any specific order required for `traction_joint_names` and `steering_joint_names` lists? Doesn't it need to know which joints are right and which are left?
> 

Does your config work with the current version without this PR? After merging, we have to fix the [ackermann_drive_controller](https://github.com/ros-controls/gz_ros2_control/blob/rolling/gz_ros2_control_demos/config/ackermann_drive_controller.yaml) of gz_ros2_control_demos, @skasperski maybe you want to work on that and create a PR there? then we can troubleshoot together if something is not working properly.

2025-02-14 08:58 UTC, christophfroehlich commented
> Ok, I will look into this. For now the parameters are misspelled in the deprecation messages. Can I somehow add commits to this PR?

you can review in the "Files changed" tab, and I can commit the changes.

2025-02-14 09:18 UTC, skasperski requested changes

2025-02-14 09:18 UTC, skasperski commented on steering_controllers_library/src/steering_controllers_library.cpp
> +      "DEPRECATED parameter 'front_steering', set 'traction_joint_names' or 'steering_joint_names' "
Parameter is actually called "traction_joints_names".

2025-02-14 09:18 UTC, skasperski commented on steering_controllers_library/test/test_steering_controllers_library.hpp
> +      traction_joints_names_[0], traction_interface_name_,
Here it is always assumed that there are exactly two joints in the order [right, left]. This is as far as I can tell not documented anywhere.

2025-02-14 09:18 UTC, skasperski commented on steering_controllers_library/src/steering_controllers_library.cpp
> +
Here it should be tested that `traction_joints_names` and `steering_joints_names` have exactly length 2, because it will crash during update if not.

2025-02-14 10:44 UTC, skasperski commented
I am currently unable to compile these packages, because all tests fail to build with this error:

```
/ros_ws/src/ros2_controllers/ackermann_steering_controller/test/test_ackermann_steering_controller.cpp:34:26: error: ‘struct steering_controllers_library::Params’ has no member named ‘traction_joints_names’
   34 |     controller_->params_.traction_joints_names, testing::ElementsAreArray(traction_joints_names_));
```

I have no idea why that is, because the generated struct does have this member. Could this be some compatibility issue between jazzy and rolling?

2025-02-14 18:34 UTC, christophfroehlich reviewed
@skasperski thanks for the hints. I pushed changes, let me know what you think.

2025-02-14 18:34 UTC, christophfroehlich commented on steering_controllers_library/test/test_steering_controllers_library.hpp
> +      traction_joints_names_[0], traction_interface_name_,
only for ackermann, and there is this note in the beginning of the test:
```
// NOTE: Testing steering_controllers_library for Ackermann vehicle configuration only
```
I added this information to the parameter yaml.

2025-02-14 18:34 UTC, christophfroehlich commented on steering_controllers_library/src/steering_controllers_library.cpp
> +      "DEPRECATED parameter 'front_steering', set 'traction_joint_names' or 'steering_joint_names' "
Fixed.

2025-02-14 18:34 UTC, christophfroehlich commented on steering_controllers_library/src/steering_controllers_library.cpp
> +
I added checks here.

2025-02-17 10:42 UTC, skasperski commented
I get this error when trying to launch the ackermann controller. It complains about the interface name, but as far as I can see it does start with the controller's name, so I am a bit clueless here:

```
[gz-1] [FATAL] [1739788697.287076537] [controller_manager]: Export of the state or reference interfaces failed with 
  following error: The name of the interface ackermann_steering_controller/linear/velocity does not begin with the 
  controller's name. This is mandatory for reference interfaces. Please correct and recompile the controller with name 
  ackermann_steering_controller and try again.
[gz-1] [INFO] [1739788697.287198080] [controller_manager]: Activating controllers: [ joint_state_broadcaster ]
[spawner-6] [ERROR] [1739788697.287824884] [spawner_ackermann_steering_controller]: Failed to configure controller

```

2025-02-17 10:53 UTC, christophfroehlich commented
have you compiled ros2_control from source? there was a recent breaking change in the way how the interfaces get exported

2025-02-17 16:29 UTC, christophfroehlich approved these changes
I applied the changes to the demo https://github.com/ros-controls/ros2_control_demos/pull/715 and it works as expected.

2025-02-18 08:20 UTC, skasperski approved these changes

2025-04-22 21:06 UTC, christophfroehlich submitted a review, later dismissed

2025-04-23 05:33 UTC, Juliaj commented on ackermann_steering_controller/test/test_ackermann_steering_controller.hpp
> +  std::vector<std::string> wheels_preceeding_names_ = {
Typo,  `wheels_preceeding` -> `wheels_preceding`. There are more instances of this typo in the current file ...

Shall we also use `joints_preceding_names_` for consistency ?

2025-04-23 07:20 UTC, christophfroehlich commented on ackermann_steering_controller/test/test_ackermann_steering_controller.hpp
> +  std::vector<std::string> wheels_preceeding_names_ = {
Good catch, fixed that in a separate PR and will merge that in here later. But we have `wheels_preceeding_names_` and `steers_preceeding_names_`, `joints` do not work then?

2025-04-23 07:59 UTC, christophfroehlich approved these changes
I just had a hard time updating https://github.com/ros-controls/gz_ros2_control/pull/566, because I misspelled a parameter.
traction_wheels_track instead of traction_wheel_track (due to the similarity to traction_wheels_radius). I propose renaming it to track_width instead.

2025-04-23 17:18 UTC, christophfroehlich commented on ackermann_steering_controller/test/test_ackermann_steering_controller.hpp
> +  std::vector<std::string> wheels_preceeding_names_ = {
done. please have a look

2025-04-23 17:42 UTC, Juliaj approved these changes
LGTM. Thanks for all the work and efforts to get this in.

2025-04-23 17:54 UTC, christophfroehlich approved these changes

2025-04-23 18:12 UTC, merged