[JTC] Report on deprecated feedback
ros-controls/ros2_controllers pull request #1172
Opened 2024-06-17 18:19 UTC by bmagyar

Even though the `desired` and `actual` fields are deprecated, we should still fill them in.

2024-06-17 18:54 UTC, saikishor approved these changes
Makes perfect sense

2024-06-17 18:57 UTC, aprotyas approved these changes

2024-06-17 20:06 UTC, bmagyar commented
FYI @MarqRazz

2024-06-17 20:34 UTC, MarqRazz reviewed
This will help with the issue I was running into but once the deprecated message is removed the new one is still missing functionality.

If I send this a trajectory you can see/plot `position, velocity, acceleration` in the `reference` value published in the `controller_state`. If I wanted to plot the `output` you can only see the values calculated for the claimed interface (i.e. `position` in my case). 

The old functionality allowed me to see/plot `position, velocity, acceleration` of the `input & output` so that I can visualize what the interpolation is doing to my trajectory.

2024-06-17 20:34 UTC, MarqRazz commented on joint_trajectory_controller/src/joint_trajectory_controller.cpp
> +    state_publisher_legacy_->msg_.actual.positions = current_state.positions;
Why only `position` for `actual`?

2024-06-19 15:47 UTC, christophfroehlich commented
> The old functionality allowed me to see/plot `position, velocity, acceleration` of the `input & output` so that I can visualize what the interpolation is doing to my trajectory.

maybe I don't get what you try to achieve, but the reference field is the interpolated output?

2024-06-19 15:48 UTC, christophfroehlich requested changes
I vote for deleting the fields instead. If there's something missing in the current design, let's discuss the roadmap proposal, implemented with https://github.com/ros-controls/control_msgs/pull/86

2024-06-19 16:53 UTC, MarqRazz commented
> maybe I don't get what you try to achieve, but the reference field is the interpolated output?

That is what I was looking for. Interesting you call the interpolated output `reference` I thought that was the input but now that I look again that is `desired`.

I'm all for removing them too!

2024-06-19 17:08 UTC, merged