Adding use of robot description parameter in the Admittance Controller
ros-controls/ros2_controllers pull request #1247
Opened 2024-08-14 14:20 UTC by destogl

Replaces #1094.

Adds propagation of `robot_description` through argument to the `kinematics_interface`.

2024-08-14 14:21 UTC, destogl commented on admittance_controller/src/admittance_controller.cpp
> +    return controller_interface::return_type::OK;
Remove skipping of large `dt`s because why to add that?

2024-08-14 14:22 UTC, destogl commented on admittance_controller/src/admittance_controller.cpp
> +
```suggestion
```

2024-08-14 15:16 UTC, saikishor approved these changes
LGTM

2024-11-05 15:26 UTC, christophfroehlich requested changes
all the tests fail, @destogl could you have a look please?

2024-11-06 21:20 UTC, saikishor approved these changes

2024-11-06 21:44 UTC, christophfroehlich approved these changes
LGTM. but some jobs failed with unrelated tests, for example from JTC. Idk why.

2024-11-06 21:47 UTC, merged

2024-11-11 17:09 UTC, destogl commented
Thanks for fixing this guys!