fix(timeout): do not reset steer wheels to 0. on timeout
ros-controls/ros2_controllers pull request #1289
Opened 2024-09-13 08:47 UTC by reinzor

Instead of setting the incoming twist command velocity to zero, we should only set the wheel commands to zero without altering the steering angles in order to avoid in-place steering of the wheels.

2024-09-19 08:01 UTC, christophfroehlich requested changes
This makes sense to me, thanks for the contribution.
Could you please have a look on the failing tests and change the assertions accordingly?
Please add also a short description in the [release_notes](https://github.com/ros-controls/ros2_controllers/blob/master/doc/release_notes.rst).

2024-09-25 20:51 UTC, bmagyar approved these changes
thank you!

2024-09-26 20:10 UTC, saikishor approved these changes

2024-09-27 07:33 UTC, christophfroehlich requested changes
Thanks for the follow-up. Just two minor comments

2024-09-27 07:33 UTC, christophfroehlich commented on steering_controllers_library/test/test_steering_controllers_library.cpp
> +  ASSERT_EQ((*(controller_->input_ref_.readFromRT()))->twist.linear.x, TEST_LINEAR_VELOCITY_X);
```suggestion
  ASSERT_EQ((*(controller_->input_ref_.readFromNonRT()))->twist.linear.x, TEST_LINEAR_VELOCITY_X);
```

2024-09-27 07:33 UTC, christophfroehlich commented on steering_controllers_library/test/test_steering_controllers_library.cpp
> +  ASSERT_EQ((*(controller_->input_ref_.readFromRT()))->twist.linear.x, TEST_LINEAR_VELOCITY_X);
```suggestion
  ASSERT_EQ((*(controller_->input_ref_.readFromNonRT()))->twist.linear.x, TEST_LINEAR_VELOCITY_X);
```

2024-09-27 09:40 UTC, christophfroehlich approved these changes

2024-10-01 08:39 UTC, merged

2024-12-29 18:40 UTC, christophfroehlich commented
@mergifyio backport humble