Restore forward command derivatives
ros-controls/ros2_controllers pull request #133
Opened 2020-12-26 21:32 UTC by bmagyar

2020-12-27 10:26 UTC, destogl requested changes
Let's move "description.hpp" where it belongs. Otherwise, very nice work!

2020-12-27 10:26 UTC, destogl commented on effort_controllers/test/descriptions.hpp
> +// Copyright 2020 ros2_control Development Team
We should take care of #133 to avoid copying this test file. (see ros-controls/ros2_control#247)

2020-12-27 10:26 UTC, destogl commented on effort_controllers/test/test_joint_group_effort_controller.cpp
> +}
This is also often used snippet when testing controllers. Should we add it into ȧ `test_resources` package?

2020-12-27 10:26 UTC, destogl commented on effort_controllers/test/test_joint_group_effort_controller.cpp
> +TEST_F(JointGroupEffortControllerTest, CommandSuccessTest)
I am guessing you are using the same test as for the general forward controller. Is that right?

2020-12-27 10:26 UTC, destogl commented on effort_controllers/test/test_joint_group_effort_controller.cpp
> +  ASSERT_EQ(joint_3_cmd_.get_value(), 3.1);
there is a specialized test for this and you repeat this snippet multiple times. Is that needed?
```suggestion
```

2020-12-27 10:26 UTC, destogl commented on forward_command_controller/src/forward_command_controller.cpp
> +  if (interface_name_.empty()) {
```suggestion
  // Specialized, child controllers set interfaces before calling init function.
  if (interface_name_.empty()) {
```

2020-12-27 10:26 UTC, destogl commented on position_controllers/src/joint_group_position_controller.cpp
> +  const std::string & controller_name)
I would prefer...

```suggestion
JointGroupPositionController::init(const std::string & controller_name)
```

2020-12-27 10:26 UTC, destogl commented on position_controllers/test/test_joint_group_position_controller.cpp
> +
same as for the effort controller
```suggestion
```

2020-12-27 10:26 UTC, destogl commented on position_controllers/test/test_joint_group_position_controller.hpp
> +
```suggestion
```

2020-12-27 10:26 UTC, destogl commented on velocity_controllers/test/test_joint_group_velocity_controller.cpp
> +namespace
same as for the effort controller

2020-12-27 10:26 UTC, destogl commented on velocity_controllers/test/test_joint_group_velocity_controller.cpp
> +
Same as for the effort and position controllers.
```suggestion
```

2021-01-02 08:28 UTC, destogl approved these changes
Looks good. `description.hpp` will be than moved in the future.

2021-01-02 19:02 UTC, merged

2021-01-06 01:17 UTC, Karsten1987 commented
so this is a API breaking change, but I haven't seen a Foxy branch. Shouldn't we have branched off before that merge?

2021-01-06 10:03 UTC, bmagyar commented
Please elaborate.