Fix RealtimeBox API changes
ros-controls/ros2_controllers pull request #1385
Opened 2024-11-23 22:57 UTC by christophfroehlich

https://github.com/ros-controls/realtime_tools/issues/200

2024-11-25 13:52 UTC, bmagyar requested changes
This PR swaps out 2 controllers' main input to use the stamped version without any deprecation. There is very little actual alignment with the realtime_tools API that I can see. Would it be possible to separate these onto 2 PRs?

2024-11-25 13:54 UTC, christophfroehlich commented
No, that is not true: There is no change! I was just puzzled by this alias and renamed it:
`using Twist = geometry_msgs::msg::TwistStamped;`
I can move that to a follow-up PR if you like to.

2024-11-26 07:25 UTC, bmagyar commented
Yes please and I stand corrected 🫡

2024-11-28 07:39 UTC, christophfroehlich commented on diff_drive_controller/src/diff_drive_controller.cpp
> +                                 { stored_value = nullptr; });
With latest fixes to realtime_tools this could stay like
```suggestion
  received_velocity_msg_ptr_.set(nullptr);
```
as the reviewers prefer.

2024-11-28 07:39 UTC, christophfroehlich commented on tricycle_controller/src/tricycle_controller.cpp
> +                                 { stored_value = nullptr; });
With latest fixes to realtime_tools this could stay like
```suggestion
  received_velocity_msg_ptr_.set(nullptr);
```
as the reviewers prefer.

2024-12-02 10:49 UTC, bmagyar approved these changes
thank you!itemize

2024-12-03 18:26 UTC, saikishor reviewed
I'm curious about the effect of the `try_get` we might have

2024-12-03 20:33 UTC, saikishor commented on diff_drive_controller/src/diff_drive_controller.cpp
> +                                     { last_command_msg = msg; });
Sounds like a nice plan!

2024-12-03 22:38 UTC, christophfroehlich commented on diff_drive_controller/src/diff_drive_controller.cpp
> +                                     { last_command_msg = msg; });
done

2024-12-03 22:46 UTC, saikishor reviewed
May be it is better to set the `last_command_msg_` to empty in the configure. Same goes for the test changes

2024-12-03 22:46 UTC, saikishor commented on diff_drive_controller/src/diff_drive_controller.cpp
>    const TwistStamped empty_twist;
```suggestion
  last_command_msg_ = std::make_shared<TwistStamped>();
```

2024-12-03 22:46 UTC, saikishor commented on diff_drive_controller/src/diff_drive_controller.cpp
> +                                 { stored_value = std::make_shared<TwistStamped>(empty_twist); });
```suggestion
                                 { stored_value = last_command_msg_; });
```

2024-12-03 23:20 UTC, christophfroehlich commented
> May be it is better to set the `last_command_msg_` to empty in the configure. Same goes for the test changes

We don't use try_get in the tests?

2024-12-04 09:29 UTC, saikishor commented
> We don't use try_get in the tests?

Sure it is not needed

2024-12-04 09:42 UTC, saikishor approved these changes
Looks spot on!

Thanks a lot for fixing things :)

2024-12-04 10:16 UTC, merged

2024-12-04 10:16 UTC, christophfroehlich commented
So we don't need to backport this after the branch-off of realtime_tools right?