[Joint State Broadcaster] Add mapping of custom states to standard values in "/joint_state" message
ros-controls/ros2_controllers pull request #217
Opened 2021-07-16 17:55 UTC by destogl

Note: it has also changes from #216 beucase it sits ontop the changes.

This mapping is useful when using multiple broadcaster to publish custom values on separate "joint_states" topic.
For example: 
1. Hydraulics robots where feedback and commanded values have offset.
   Typically one would map both values in separete interfaces inthe framework.
   To visualize those data mutiple JSB's and `robot_state_publishers` would be used to visualize both values in RViz.

1. A robot provides different measuring tequniques for its joint values which results in slightly differnt values.
   Typically one would use separate interface for providing those values in the framework. 
   Using multiple JSB's we could publish and show both in RViz.

2021-11-29 15:25 UTC, bmagyar commented
hello, could you please rebase this?

2021-12-12 11:18 UTC, bmagyar requested changes

2021-12-23 16:18 UTC, destogl commented on joint_state_broadcaster/doc/userdoc.rst
> +  Format (each line is optional):
What do you think about added examples?

2021-12-26 19:17 UTC, bmagyar approved these changes

2021-12-28 21:00 UTC, merged