Add support for publishing additional topics to the FTS Broadcaster
ros-controls/ros2_controllers pull request #268
Opened 2021-11-16 14:43 UTC by destogl

This has to be cleaned a bit to split "additional topics" and filtering functionalities into separate PRs.

2021-11-19 00:53 UTC, bmagyar commented on force_torque_sensor_broadcaster/src/force_torque_sensor_broadcaster.cpp
>  #include <string>
```suggestion
#include <string>
#include <vector>
```

2021-11-19 00:59 UTC, bmagyar requested changes
Looks good to me but please please add 2 new tests:
* checking the wrench
* checking additional frames

2023-05-16 11:22 UTC, bmagyar commented
@destogl are you ready to move this ahead?

2025-04-15 17:27 UTC, christophfroehlich commented
included in #559

2025-04-15 17:27 UTC, closed without merging