Fix linking of target `test_load_joint_trajectory_controller`
ros-controls/ros2_controllers pull request #309
Opened 2022-03-07 10:52 UTC by kb0n

Fixes "No such file or directory" error:
`joint_trajectory_controller.hpp:27:10: fatal error: control_toolbox/pid.hpp: No such file or directory`

It needs `control_toolbox`, but depends on `joint_trajectory_controller` anyway. Hence the single-target linking, just as it is done for all other test-targets here as well.

fixup for 1fd8bc37f284098aed39d4e6bd324a8528a72ad4

2022-03-07 11:49 UTC, bmagyar commented
hi,

the change seems sensible but I wonder how come we did not see this issue come up on the CI. What OS are you running / what ROS distro?

2022-03-07 14:00 UTC, kb0n commented
> hi,
> 
> the change seems sensible but I wonder how come we did not see this issue come up on the CI. What OS are you running / what ROS distro?

I'm on Debian 11 (bullseye), using a rather recent ros2-rolling installation according to https://docs.ros.org/en/rolling/Installation/Ubuntu-Development-Setup.html

2022-03-08 20:55 UTC, JafarAbdi approved these changes
We run into the same issue today in our CI

2022-03-12 16:12 UTC, destogl commented
No, this is not an issue! The point of the test is to load JTC using pluginlib, as controller manger would do. And having controller manager to be linked to all and every controller is not only impossible, but also not intended.

2022-03-25 14:38 UTC, bmagyar commented
I agree that this only happens to accidentally fix it but it is quite a nuclear solution.
How about adding `control_toolbox` to `ament_target_dependencies` for this test?

Note that it'd also be nice to reproduce this with a CI somehow.

2022-03-25 14:39 UTC, bmagyar requested changes
I agree that this only happens to accidentally fix it but it is quite a nuclear solution.
How about adding control_toolbox to ament_target_dependencies for this test?

Note that it'd also be nice to reproduce this with a CI somehow.

2022-04-10 07:07 UTC, bmagyar commented
Closing in favour of #319 , please reopen if issue still persists

2022-04-10 07:07 UTC, closed without merging