port rqt_joint_trajectory_controller to ros2
ros-controls/ros2_controllers pull request #356
Opened 2022-05-18 08:26 UTC by Noel215

Port over the package rqt_joint_trajectory_controller from https://github.com/ros-controls/ros_controllers/tree/noetic-devel/rqt_joint_trajectory_controller, which implements the rqt GUI to control the joint_trajectory_controller instances

PR for the following issue [#313](https://github.com/ros-controls/ros2_controllers/issues/313)

2022-05-19 06:18 UTC, homalozoa requested changes

2022-05-19 06:18 UTC, homalozoa commented on rqt_joint_trajectory_controller/plugin.xml
> +</library>
Add new line here, please.

2022-05-19 06:18 UTC, homalozoa commented on rqt_joint_trajectory_controller/setup.cfg
> +install-scripts=$base/lib/rqt_joint_trajectory_controller
New line here, too.

2022-05-19 14:28 UTC, homalozoa approved these changes

2022-06-15 07:11 UTC, bmagyar requested changes

2022-06-27 23:14 UTC, Noel215 commented
The requested changes were pushed. I've been checking the failures in the workflows but all of them are related to other packages so I don't know how to continue with this PR

2022-07-26 05:52 UTC, bmagyar approved these changes

2022-07-29 07:19 UTC, bmagyar commented
Sorry for the wait, I did a bit of simulation testing and will have a couple of follow-up tasks but this is good to go as-is! Thanks for sticking around

2022-07-29 07:19 UTC, merged