Odom Topic & Frame Namespaces
ros-controls/ros2_controllers pull request #461
Opened 2022-11-07 11:13 UTC by sp-sophia-labs

## Description

The goal of this PR is to enable namespaces on diff_drive_controller for the odom topic and the odom frame 

## How has this been tested?

We have tested this code on create3 and turtlebot4 robots. You can find our project here: https://github.com/sp-sophia-labs/turtlebot4_multi_sim.  Reviewers may clone the project and replicate exactly what we use for testing (you can find the details in the project's README)

## Checklist

- [ ] Lint code with appropriate parser

2022-11-08 09:18 UTC, bmagyar commented
I'd really prefer to merge this into `master` and backport to Galactic. Is that ok with you? I know you've tested it in Galactic

2022-11-09 12:46 UTC, sp-sophia-labs commented
@bmagyar No problem for me, I've rebased the changes on master and fixed the linting with `pre-commit`

2022-11-09 20:46 UTC, bmagyar commented on diff_drive_controller/src/diff_drive_controller.cpp
> +  std::string controller_namespace = std::string(node_->get_namespace());
```suggestion
  std::string controller_namespace = std::string(get_node()->get_namespace());
```
I think it's something like this in the new api

2022-11-09 21:14 UTC, bmagyar approved these changes

2022-11-12 07:56 UTC, bmagyar reviewed
Assign namespace prefix directly to odom_params to simplify code

2022-11-12 07:58 UTC, bmagyar requested changes
Assign namespace prefix directly to odom_params to simplify code

2022-11-12 08:09 UTC, bmagyar approved these changes

2022-11-12 08:13 UTC, destogl approved these changes

2022-11-12 08:15 UTC, bmagyar commented on diff_drive_controller/src/diff_drive_controller.cpp
> +  odometry_message.child_frame_id = controller_namespace + odom_params_.base_frame_id;
```suggestion
  odom_params_.base_frame_id = controller_namespace + odom_params_.base_frame_id;
```

2022-11-12 10:34 UTC, merged