Porting ackermann steering controller to ros2
ros-controls/ros2_controllers pull request #466
Opened 2022-11-16 17:27 UTC by Robotgir

2022-11-17 19:04 UTC, destogl commented
@ijnek can you take a look at this PR? Would this Ackerman controller be also applicable for you? Do we have to add some functionality here?

2022-12-02 21:31 UTC, willcbaker commented
+1 friendly bump, is there any outstanding work to be done to land these controllers?

2022-12-03 01:19 UTC, ijnek commented
I was going to take a look at this but I'm not quite finding the time for it... would someone else be able to review this?

2022-12-06 12:17 UTC, bmagyar commented
@willcbaker let me help you with that

2022-12-06 14:23 UTC, closed without merging

2022-12-06 14:27 UTC, bmagyar requested changes
![73bq3x](https://user-images.githubusercontent.com/3524577/205938136-268f742c-02e3-4ec4-90cc-2e0922c12ffe.jpg)

2022-12-06 14:27 UTC, bmagyar commented on ackermann_steering_controller/test/test_ackermann_steering_controller.cpp
> +  // 0.0);
commented