Broadcaster parameters
ros-controls/ros2_controllers pull request #650
Opened 2023-06-05 18:48 UTC by christophfroehlich

`imu_sensor_broadcaster` and `force_torque_sensor_broadcaster` had parameters manually parsed for being non-empty. I added them to the generate_parameter_library yaml and updated the tests accordingly.

2023-06-12 15:49 UTC, destogl approved these changes
Thanks!

2023-06-12 16:53 UTC, bmagyar requested changes

2023-06-12 16:53 UTC, bmagyar commented on force_torque_sensor_broadcaster/test/test_force_torque_sensor_broadcaster.cpp
> +  ::testing::InitGoogleTest(&argc, argv);
we use Google Mock in all:

```suggestion
  ::testing::InitGoogleMock(&argc, argv);
```

2023-06-13 09:09 UTC, christophfroehlich commented on force_torque_sensor_broadcaster/test/test_load_force_torque_sensor_broadcaster.cpp
> +  ::testing::InitGoogleTest(&argc, argv);
```suggestion
  ::testing::InitGoogleMock(&argc, argv);
```

2023-06-13 09:11 UTC, christophfroehlich commented on imu_sensor_broadcaster/test/test_imu_sensor_broadcaster.cpp
> +  ::testing::InitGoogleTest(&argc, argv);
```suggestion
  ::testing::InitGoogleMock(&argc, argv);
```

2023-06-13 09:11 UTC, christophfroehlich commented on imu_sensor_broadcaster/test/test_load_imu_sensor_broadcaster.cpp
> +  ::testing::InitGoogleTest(&argc, argv);
```suggestion
  ::testing::InitGoogleMock(&argc, argv);
```

2023-06-14 11:44 UTC, bmagyar approved these changes
Thank you!

2023-06-14 11:45 UTC, merged