[JTC] Use time of the last command for set_point_before_trajectory_msg in open-loop mode
ros-controls/ros2_controllers pull request #780
Opened 2023-09-26 16:18 UTC by destogl

This PR tackles the issues that happen in open-loop mode where on replacing trajectories the last command is repeated.
The figures below show the results of the output trajectories before and after this functionality. The trajectory that uses the time of the last command as point before trajectory messages gets smoother output.

Functionality right now:
![When using current time](https://github.com/ros-controls/ros2_controllers/assets/1918204/68638397-959a-4534-9f44-6c4aa69983c9)

Functionality with this PR:
![With using previous time with previous command](https://github.com/ros-controls/ros2_controllers/assets/1918204/84a48981-66e7-4838-8d59-fb7a70a4cd97)

P.S. The similar thing would be useful for trajectory replacement in closed loop mode, but then we would need to know exactly when the state is read from the hardware. This is just something to think about in the future.

P.P.S. I will add tests too.

2023-10-02 15:07 UTC, christophfroehlich reviewed
Looks good for me (even more if the mentioned tests are added)
concerning closed-loop mode: I'm not sure if this is necessary, shouldn't the trajectory generator be aware of the current state? But I guess there might be configurations where this could improve something.

2023-10-03 15:25 UTC, christophfroehlich commented
I'm asking myself if it is desirable at all to interpolate from measured state instead of the last command with closed-loop config. but that really depends on the algorithm generating the trajectory

2024-11-02 14:07 UTC, christophfroehlich requested changes
`test_no_jump_when_state_tracking_error_not_updated` fails

2025-02-12 20:28 UTC, christophfroehlich approved these changes
LGTM, I fixed the test now.

2025-02-14 14:50 UTC, Thieso commented on joint_trajectory_controller/test/test_trajectory_controller.cpp
> +  // JTC is NOT executing trajectory in open-loop therefore:
`open-loop` needs to be `interpolate_from_desired_state`

2025-02-14 14:51 UTC, Thieso commented on joint_trajectory_controller/test/test_trajectory_controller.cpp
>    // JTC is executing trajectory in open-loop therefore:
`open-loop` needs to be `interpolate_from_desired_state`

2025-02-14 14:52 UTC, Thieso requested changes
Looks good to me, just need to change `open-loop`  to be `interpolate_from_desired_state` according to #1525  but I do not have the permissions for this

2025-02-14 16:02 UTC, christophfroehlich commented
for this PR it is fine with open-loop, if you approve we can merge that immediately. we then can change that in your PR, where we have to wait for a review of another maintainer anyways

2025-02-14 21:32 UTC, Thieso approved these changes

2025-02-14 21:59 UTC, merged