Ackermann steering fix. issue #878
ros-controls/ros2_controllers pull request #921
Opened 2023-12-12 07:59 UTC by franzrammerstorfer

This is IMHO a quick and easy fix for 

https://github.com/ros-controls/ros2_controllers/issues/878

2023-12-12 10:03 UTC, christophfroehlich requested changes
Hi @franzrammerstorfer! Thanks for the PR. 

Some first comments from my side:

To fix the linter issues, you can check it locally by
- install pre-commit by `pip3 install pre-commit`
- `pre-commit run--all`

Why do you use `EXPECT_FLOAT_EQ` instead of `EXPECT_DOUBLE_EQ`?

Does it make sense to check these cases also with `update_from_velocity` and `update_from_position`, i.e., for `params_.open_loop=false`?

2023-12-12 11:08 UTC, franzrammerstorfer commented
Hi @christophfroehlich!
Sorry for not listen to pre-commit checks, I did not read the instructions carefully enough. I think I fixed that with my last few commits. I misused EXPECT_FLOAT_EQ, bad habit, thanks for the hint.

Yes, you're right, there are a lot of things open to test -- but right now I just wanted to provide a quick fix for the Ackermann odometry, only rudimentary tested. Maybe we should open a new issue, tagged "help wanted" for proper testing of the steering lib -- starting with tests for the integrator functions, etc. But maybe first we should check for a redesign cf. #692

BTW, I just added this file 'test_steering_odometry.cpp', with some hard-coded tests. Is that the way to go, or do we want to have a more advanced testing style?

2023-12-12 11:27 UTC, christophfroehlich commented
> Yes, you're right, there are a lot of things open to test -- but right now I just wanted to provide a quick fix for the Ackermann odometry, only rudimentary tested. Maybe we should open a new issue, tagged "help wanted" for proper testing of the steering lib -- starting with tests for the integrator functions, etc. But maybe first we should check for a redesign cf. #692

ok, I'll create a new issue then.

> BTW, I just added this file 'test_steering_odometry.cpp', with some hard-coded tests. Is that the way to go, or do we want to have a more advanced testing style?

Should the expectations of the FW kinmatics be true for all the different kinematic configurations? Then we could change this to a parameterized test as we have with JTC
https://github.com/ros-controls/ros2_controllers/blob/1d0d7531ef8d24ea52e761a872b8bf277652dd33/joint_trajectory_controller/test/test_trajectory_controller_utils.hpp#L695-L710

https://github.com/ros-controls/ros2_controllers/blob/1d0d7531ef8d24ea52e761a872b8bf277652dd33/joint_trajectory_controller/test/test_trajectory_controller.cpp#L1840-L1849

2023-12-12 13:19 UTC, christophfroehlich commented
But we can for now just fix the CI and extend the tests in a follow-up PR.

2023-12-14 07:52 UTC, christophfroehlich commented
@aleksandrsizmailovs and @roncapat, as you have commented on the issue: Is this PR fine for you?

2023-12-14 07:52 UTC, christophfroehlich approved these changes
LGTM

2023-12-14 07:53 UTC, roncapat commented
Seems fine IMHO :)

2023-12-15 08:24 UTC, aleksandrsizmailovs commented
> @aleksandrsizmailovs and @roncapat, as you have commented on the issue: Is this PR fine for you?

Looks good to me.

2023-12-30 20:24 UTC, bmagyar commented on steering_controllers_library/test/test_steering_odometry.cpp
> +  // std::cout << "\nsteer left (inner)" << cmd1[1] << std::endl;
```suggestion
```

2023-12-30 20:24 UTC, bmagyar commented on steering_controllers_library/test/test_steering_odometry.cpp
> +  // std::cout << "\nsteer left (outer)" << cmd1[1] << std::endl;
```suggestion
```

2023-12-30 20:25 UTC, bmagyar approved these changes

2023-12-30 20:25 UTC, merged