run gh actions on 20.04
ros-controls/ros2_controllers pull request #98
Opened 2020-09-22 15:54 UTC by Karsten1987

Signed-off-by: Karsten Knese <Karsten1987@users.noreply.github.com>

2020-09-24 14:07 UTC, destogl approved these changes
Looks good to me

2020-09-24 19:35 UTC, bmagyar approved these changes

2020-09-24 19:36 UTC, bmagyar requested changes
This PR is a big of a misnomer. The title suggests a fix which was done but you also disabled the industrial_ci job and codecov. Care to detail?

2020-09-24 21:35 UTC, destogl commented
See my comment in ros-controls/ROS2-control#159

2020-09-25 18:23 UTC, Karsten1987 commented
I reverted the conditional given that we target only Foxy. Also adopted the description of the PR

2020-09-25 18:25 UTC, Karsten1987 commented
@destogl @bmagyar please review.

2020-09-26 13:43 UTC, destogl approved these changes

2020-09-26 13:43 UTC, destogl commented on .github/workflows/ci.yml
> +  #          - {ROS_DISTRO: foxy, ROS_REPO: main}
```suggestion
  #          - {ROS_DISTRO: foxy, ROS_REPO: main}
  #          - {ROS_DISTRO: foxy, ROS_REPO: testing}
```

2020-09-26 17:42 UTC, merged